services:
  backend:
    build: ./backend
    container_name: student-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: student-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
    depends_on:
      - backend
