apiVersion: v1
kind: ConfigMap
metadata:
  name: student-app-configmap
  namespace: student-app

data:
  DB_URL: "jdbc:mariadb://student-app-db.cp080wim6qax.ap-south-1.rds.amazonaws.com:3306/student_db"
  DB_PORT: "3306"
  DB_NAME: student_db